<UserControl x:Class="AsyncAwaitPain.WPF.ExceptionView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:AsyncAwaitPain.WPF"
             mc:Ignorable="d" 
             d:DesignHeight="300" d:DesignWidth="300"
             x:Name="ucException">
    <Border>
        <StackPanel>
            <TextBlock Text="Exception"></TextBlock>
            <TextBlock Text="{Binding Path=Count, ElementName=ucException, FallbackValue=NaN}"></TextBlock>
            <Button x:Name="Abandon" Click="Abandon_Click">Abandon</Button>
            <Button x:Name="AsyncVoid" Click="AsyncVoid_Click">Async Void</Button>
            <Button x:Name="AbandonTryCatch" Click="AbandonTryCatch_Click">Abandon Try/Catch</Button>
            <Button x:Name="AsyncVoidTryCatch" Click="AsyncVoidTryCatch_Click">Async Void Try/Catch</Button>
        </StackPanel>
    </Border>
</UserControl>
